apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: hamper
    secureJsonData:
      password: hamper_secret
    jsonData:
      database: hamper_forecast
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
    uid: Postgres
